<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12" PrivateAssets="all" />
    <ProjectReference Include="..\VisoERP.Application\VisoERP.Application.csproj" />
    <ProjectReference Include="..\VisoERP.Infra.Ioc\VisoERP.Infra.Ioc.csproj" />
    <ProjectReference Include="..\VisoERP.Infra.Helper\VisoERP.Infra.Helper.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <UserSecretsId>VisoERP-Web</UserSecretsId>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
